bind 127.0.0.1 ::1
protected-mode yes
port 6379
daemonize no
supervised no
dir /mnt/workspace/songdance/redis
appendonly yes
appendfsync everysec
save 60 1
maxmemory 256mb
maxmemory-policy noeviction
logfile ""
